export enum EIFoodNegotiationReasons {
  HIGH_STORE_DEMAND = 'HIGH_STORE_DEMAND',
  STORE_SYSTEM_ISSUES = 'STORE_SYSTEM_ISSUES',
  LACK_OF_DRIVERS = 'LACK_OF_DRIVERS',
  OPERATIONAL_ISSUES = 'OPERATIONAL_ISSUES',
  ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY',
  DRIVER_IS_ALREADY_AT_THE_ADDRESS = 'DRIVER_IS_ALREADY_AT_THE_ADDRESS',
  OTHER_REASONS = 'OTHER_REASONS',
}
