export { ProductCategory as CannoliProductCategory } from './category.interfcace';
export { CompanyInfo as CannoliCompanyInfo } from './company-info';
export { EngineStatistic as CannoliEngineStatistic } from './engine-statistics.interface';
export { IBucket as CannoliIBucket } from './i-bucket';
export { ICampaign as CannoliICampaign   } from './i-campaign';
export { ICampaignRule as CannoliICampaignRule } from './i-campaign-rule';
export { ICampaignSponsorship as CannoliICampaignSponsorship } from './i-campaign-sponsorship';
export { ICompany as CannoliICompany  } from './i-company';
export { ICompanyAddress as CannoliICompanyAddress } from './i-company-address';
export { ICompanyKeys as CannoliICompanyKeys } from './i-company-keys';
export { ILatLng as CannoliILatLng } from './i-company-lat-lng';
export { ICompanyMessage as CannoliICompanyMessage } from './i-company-message';
export { ICompanyPaymentProvider as CannoliICompanyPaymentProvider } from './i-company-payment-provider';
export { ICompanyPaymentProviderAgent as CannoliICompanyPaymentProviderAgent } from './i-company-payment-provider-agent';
export { ICompanyPaymentProviderPaymentMethod as CannoliICompanyPaymentProviderPaymentMethod } from './i-company-payment-providers-payments-method';
export { ICompanyPaymentProviderPaymentMethodData as CannoliICompanyPaymentProviderPaymentMethodData } from './i-company-payment-providers-payments-method-data';
export { IDeliverer as CannoliIDeliverer } from './i-deliverer';
export { IDeliveryArea as CannoliIDeliveryArea  } from './i-delivery-area';
export { IDeliveryAreaFixed as CannoliIDeliveryAreaFixed  } from './i-delivery-area-fixed';
export { IDesenfilaCustomer as CannoliIDesenfilaCustomer } from './i-desenfila-customer';
export { IDesenfilaCustomerAddress as CannoliIDesenfilaCustomerAddress } from './i-desenfila-customer-address';
export { IDesenfilaCustomerIdentification as CannoliIDesenfilaCustomerIdentification } from './i-desenfila-customer-identification';
export { IDesenfilaCustomerPhone as CannoliIDesenfilaCustomerPhone } from './i-desenfila-customer-phone';
export { IDesenfilaOrder as CannoliIDesenfilaOrder } from './i-desenfila-order';
export { IDesenfilaOrderItem as CannoliIDesenfilaOrderItem } from './i-desenfila-order-item';
export { IDesenfilaPaymentItemV3 as CannoliIDesenfilaPaymentItemV3 } from './i-desenfila-payment-item-v3';
export { IDesenfilaPaymentV3 as CannoliIDesenfilaPaymentV3 } from './i-desenfila-payment-v3';
export { IDesenfilaPreference as CannoliIDesenfilaPreference } from './i-desenfila-preference';
export { IDesenfilaPreferenceItem as CannoliIDesenfilaPreferenceItem } from './i-desenfila-preference-item';
export { IDesenfilaPreferencePayer as CannoliIDesenfilaPreferencePayer } from './i-desenfila-preference-payer';
export { IDesenfilaPreferencePayerAddress as CannoliIDesenfilaPreferencePayerAddress } from './i-desenfila-preference-payer-address';
export { IDesenfilaPreferencePayerIdentification as CannoliIDesenfilaPreferencePayerIdentification } from './i-desenfila-preference-payer-identification';
export { IDesenfilaPreferencePayerPayment as CannoliIDesenfilaPreferencePayerPayment } from './i-desenfila-preference-payer-payment';
export { IDesenfilaPreferencePayerPhone as CannoliIDesenfilaPreferencePayerPhone } from './i-desenfila-preference-payer-phone';
export { IDesenfilaPublicKey as CannoliIDesenfilaPublicKey } from './i-desenfila-public-key';
export { IDevice as CannoliIDevice  } from './i-device';
export { IDeviceApp as CannoliIDeviceApp } from './i-device-app';
export { IDeviceAppConfig as CannoliIDeviceAppConfig } from './i-device-app-configs';
export { IDeviceCheckout as CannoliIDeviceCheckout } from './i-device-checkout';
export { IDeviceCheckoutConfigTef as CannoliIDeviceCheckoutConfigTef } from './i-device-checkout-config-tef';
export { IDeviceCheckoutConfigTefApi as CannoliIDeviceCheckoutConfigTefApi } from './i-device-checkout-config-tef-api';
export { IDeviceCheckoutConfigTefApi } from './i-device-checkout-config-tef-api';
export { IDeviceCheckoutConfig as CannoliIDeviceCheckoutConfig } from './i-device-checkout-configs';
export { IDeviceCheckoutPaymentsOnline as CannoliIDeviceCheckoutPaymentsOnline } from './i-device-checkout-payments-online';
export { IDeviceCheckoutPicture as CannoliIDeviceCheckoutPicture } from './i-device-checkout-picture';
export { IDeviceCheckoutPicture } from './i-device-checkout-picture';
export { IDeviceCustomText as CannoliIDeviceCustomText } from './i-device-custom-text';
export { IDeviceMenu as CannoliIDeviceMenu } from './i-device-menu';
export { IDeviceScreen as CannoliIDeviceScreen } from './i-device-screen';
export { IDeviceScreenBoard as CannoliIDeviceScreenBoard } from './i-device-screen-board';
export { IDiffraction as CannoliIDiffraction, IDiffractionVariation } from './i-diffraction';
export { IEngine as CannoliIEngine } from './i-engine';
export { IEngineCredential as CannoliIEngineCredential } from './i-engine-credential';
export { IEngineFees as CannoliIEngineFees } from './i-engine-fees';
export { IEnginePayment as CannoliIEnginePayment } from './i-engine-payment';
export { IEntity as CannoliIEntity } from './i-entity';
export { IEpadocaStore as CannoliIEpadocaStore } from './i-epadoca-store';
export { IEpadocaToken as CannoliIEpadocaToken } from './i-epadoca-token';
export { IGeocode as CannoliIGeocode } from './i-geocode';
export { IGeocodeEnvelopeArray as CannoliIGeocodeEnvelopeArray } from './i-geocode-envelope-array';
export { IGlobalsProduct as CannoliIGlobalsProduct } from './i-globals-product';
export { IRating as CannoliIRating } from './i-globals-rating';
export { IGlobalsUtilization as CannoliIGlobalsUtilization } from './i-globals-utilizations';
// export { IIFoodCategoryItem as CannoliIIFoodCategoryItem } from './i-ifood-category-item';
export { IIFoodToken as CannoliIIFoodToken, IIFoodV1Token, IIFoodV2Token } from './i-ifood-token';
export { IMember as CannoliIMember } from './i-member';
export { IMenuConfig as CannoliIMenuConfig } from './i-menu-config';
export { IMenuScheduleV2 as CannoliIMenuScheduleV2 } from './i-menu-schedule-v2';
export { IMenuV2 as CannoliIMenuV2 } from './i-menu-v2';
export { IMerchant as CannoliIMerchant } from './i-merchant';
export { IMerchantAddress as CannoliIMerchantAddress } from './i-merchant-address';
export { IOrderActionV3 as CannoliIOrderActionV3 } from './i-order-action-v3';
export { IOrderAditionalFeeV3 as CannoliIOrderAditionalFeeV3 } from './i-order-additional-fees-v3';
export { IOrderCancellationV3 as CannoliIOrderCancellationV3 } from './i-order-cancellation-v3';
export { IOrderCustomerV3 as CannoliIOrderCustomerV3, IOrdersCustomerPhone as CannoliIOrdersCustomerPhone } from './i-order-customer-v3';
export { IOrderDelivererV3 as CannoliIOrderDelivererV3 } from './i-order-deliverer-v3';
export { IOrderDeliveryAddressV3 as CannoliIOrderDeliveryAddressV3 } from './i-order-delivery-address-v3';
export { IOrderDeliveryV3 as CannoliIOrderDeliveryV3 } from './i-order-delivery-v3';
export { IOrderDesenfilaV3 as CannoliIOrderDesenfilaV3 } from './i-order-desenfila-v3';
export { IOrderIndoorV3 as CannoliIOrderIndoorV3 } from './i-order-indoor-v3';
export { IOrderItemComposition as CannoliIOrderItemComposition } from './i-order-item-composition';
export { IOrderItemOptionV3 as CannoliIOrderItemOptionV3 } from './i-order-item-option-v3';
export { IOrderItemScaleV3 as CannoliIOrderItemScaleV3 } from './i-order-item-scales-v3';
export { IOrderItemScalePricesV3 as CannoliIOrderItemScalePricesV3, IOrderItemV3 } from './i-order-item-v3';
export { IOrderMerchantV3 as CannoliIOrderMerchantV3 } from './i-order-merchant-v3';
export { IOrderOccurrence as CannoliIOrderOccurrence } from './i-order-occurrence';
export {
  IOrderPaymentCard as CannoliIOrderPaymentCard,
  IOrderPaymentCash as CannoliIOrderPaymentCash,
  IOrderPaymentMethodV3 as CannoliIOrderPaymentMethodV3,
  IOrderPaymentPix as CannoliIOrderPaymentPix,
  IOrderPaymentWallet as CannoliIOrderPaymentWallet,
} from './i-order-payment-method-v3';
export { IOrderPaymentV3 as CannoliIOrderPaymentV3 } from './i-order-payment-v3';
export { IOrderTakeoutV3 as CannoliIOrderTakeoutV3 } from './i-order-takeout-v3';
export { IOrderTotalV3 as CannoliIOrderTotalV3 } from './i-order-total-v3';
export { IOrderV3 } from './i-order-v3';
export { IPartner as CannoliIPartner } from './i-partner';
export { IPaymentMethod as CannoliIPaymentMethod } from './i-payment-method';
export { IPoint as CannoliIPoint } from './i-point';
export { EPreparingStatus as CannoliEPreparingStatus, IPreparing, IPreparingItem } from './i-preparing';
export { IPrintInfo as CannoliIPrintInfo } from './i-print-info';
export { IProduct as CannoliIProduct } from './i-product';
export { IProductCategory as CannoliIProductCategory } from './i-product-category';
export { IProductComposition as CannoliIProductComposition } from './i-product-composition';
export { IProductDetailV2 as CannoliIProductDetailV2 } from './i-product-detail-v2';
export { IProductOptionsTypeV2 as CannoliIProductOptionsTypeV2 } from './i-product-options-types';
export { IProductOptionsV2 as CannoliIProductOptionsV2 } from './i-product-options-v2';
export { IProductQuestion as CannoliIProductQuestion } from './i-product-question';
export { IProductSectionMenu as CannoliIProductSectionMenu } from './i-product-section-menu';
export { IProductSectionSchedule as CannoliIProductSectionSchedule } from './i-product-section-schedule';
export { IProductSizesV2 as CannoliIProductSizesV2 } from './i-product-sizes-v2';
export { IProductToppingV2 as CannoliIProductToppingV2 } from './i-product-topping-v2';
export { IProductV2 as CannoliIProductV2 } from './i-product-v2';
export { IProductionPlace as CannoliIProductionPlace } from './i-production-place';
export { IQrToken as CannoliIQrToken } from './i-qr-token';
export { IQuestionV2 as CannoliIQuestionV2 } from './i-question';
export { IQuestionOptionsV2 as CannoliIQuestionOptionsV2 } from './i-question-options';
export { IResumeCoords as CannoliIResumeCoords } from './i-resume-coords';
export { IResumeCoordsCoordinates as CannoliIResumeCoordsCoordinates } from './i-resume-coords-coordinates';
export { ISectionMenu as CannoliISectionMenu } from './i-section-menu';
export { ISettingMarketplaceTax as CannoliISettingMarketplaceTax } from './i-setting-marketplace-tax';
export { ISubscriptionMessage as CannoliISubscriptionMessage } from './i-subscription-message';
export { ITab as CannoliITab } from './i-tab';
export { IToken as CannoliIToken } from './i-token';
export { ITopic as CannoliITopic } from './i-topic';
export { ITopping as CannoliITopping } from './i-topping';
export { IUbereatsAuth as CannoliIUbereatsAuth } from './i-ubereats-auth';
export { IUbereatsEvent as CannoliIUbereatsEvent } from './i-ubereats-event';
export { IUsedCampaign as CannoliIUsedCampaign } from './i-used-campaign';
export { IViaCep as CannoliIViaCep } from './i-viacep';
export { JwtPayload as CannoliJwtPayload } from './jwt.payload';
export { Observation as CannoliObservation } from './observation.interface';
export { ProductBlend as CannoliProductBlend } from './product-bland.interface';
export { ProductBlendItemProduct as CannoliProductBlendItemProduct } from './product-blend-item-product.interface';
export { ProductBlendItem as CannoliProductBlendItem } from './product-blend-item.interface';
export { IProductChild as CannoliIProductChild } from './product-child.interface';
export { ProductInput as CannoliProductInput } from './product-input.interface';
export { IProductBase as CannoliIProductBase } from './product-interface';
export { ProductLinkInput as CannoliProductLinkInput } from './product-link-input.interface';
export { IProductParent as CannoliIProductParent } from './product-parent.interface';
export { ProductSimpleQuestion as CannoliProductSimpleQuestion } from './product-simple-question.interface';
export { IProductSimple as CannoliIProductSimple } from './product-simple.interface';
export { StatisticsProduct as CannoliStatisticsProduct } from './statistics-product.interface';
export { IStatistics as CannoliIStatistics } from './statistics.interface';
export { TaxConfig as CannoliTaxConfig } from './tax-config.interface';
export { IDeviceAppImages } from './i-device-app-images';

