/* eslint-disable @typescript-eslint/naming-convention */
export enum OrderPaymentIdEnum {
    cash = 'BA6AefaUeWAewpvRM5qw',
    pix = 'paQUVKhfFiTNCxxhhmDE',
    credit = 'taLf28N6nSJf85a3L0TO',
    debit = 'jiNP6vv5pBexhHAT2juS',
    refeisul = '1y6GvgAd620Xl1ycoWnG',
    ben = '5QJ0a9stbf68m49DtmLu',
    dinersClub = '9hE5sFqixwqmNADQCgvU',
    greenCard = '9ONr41iiC9BeXiO9T2sE',
    elo = '38x8wxRNZY7QLOfbkjnz',
    americanExpress = 'a2uBNqVhCG9CVed6k2uI',
    nugo = 'DQouVe6eIg9Zu9WEumNs',
    nutriCard = 'EpLTserWX5ySL2eQO3bs',
    visa = 'EtAUR4iet9UskmFtcnNP',
    visaRefeicao = 'eu13NPIrshPvB61GOSWx',
    hipercard = 'EZ0fsJq1jOOfWtr4wFrC',
    sodexo = 'F21ViC8KafOK5WlF5Q9m',
    goodCard = 'fRcKj3GMbdrlFC0460E2',
    valeCard = 'fT45nD2huzvK7MMIPgrL',
    // = "GFctAUoNPhxWUUTJShs0",
    // = "hAQrFVXJXMpmLOfruhRs",
    cooperCard = 'hlxVYOxsao6z3fTuRAFc',
    veroCard = 'ibicpwoTM3HENbtA0uJL',
    verdeCard = 'IBSoWoIkVht7U7a7LV0G',
    banriCompras = 'jkAGe5BhWZpB3fysj9mP',
    // = "nQIKSFYh12tXULrov62V",
    // = "q0sNipVj0sViOSHQma",
    alelo = 'W5nc8aFeGuzTu1PS1hZ3',
    // = "wgFU3hXpMeWouJoIG8nJ",
    vrBeneficios = 'wIivHn52tgQ0K1tsiZ8C',
    mastercard = 'WurVno6ZHmlNsBAAzLyc',
    ticket = 'zUaMtP0tXKPDhMWpEYgq',
}
