export enum EImageFolder {
  COMPANIES = 'companies',
  CUSTOMERS = 'customers',
  MEMBERS = 'members',
  // MENU_CATEGORIES = 'menu-categories',
  MENUS = 'menus',
  SECTIONS = 'sections',
  PRODUCTS = 'products',
  COMPOSITIONS = 'compositions',
  TYPES = 'types',
  PRODUCT_SIZES = 'product-sizes',
  TOPPINGS = 'toppings',
  DEVICE = 'device',
  TAA = 'taa',
  IN_TAB = 'in-tab',
  TOP = 'top',
  DELIVERERS = 'deliverers',
  DEFAULT = 'default',
}