export enum EImageFolder {
  COMPANIES = 'companies',
  CUSTOMERS = 'customers',
  DELIVERERS = 'deliverers',
  DEVICE = 'device',
  MEMBERS = 'members',
  MENU_CATEGORIES = 'menu-categories',
  MENUS = 'menus',
  PRODUCTS = 'products',
  TOPPINGS = 'toppings',
  SECOES = 'secoes',
  TAA = 'taa',
  IN_TAB = 'in-tab',
  TOP = 'top',
  DEFAULT = 'default',
}