export enum EPayioRole {
  MEMBERS = 'MEMBERS',
  COMPANIES = 'COMPANIES',
  PRODUCTS = 'PRODUCTS',
  ORDERS = 'ORDERS',
  PAYMENTS = 'PAYMENTS',
  SETTINGS = 'SETTINGS',
  GENERAL = 'GENERAL',
  ACCOUNT = 'ACCOUNT',
  CHEF_CONFIG = 'CHEF_CONFIG',
  CHEF_SCHEDULE = 'CHEF_SCHEDULE',
  CASH_CONFIG = 'CASH_CONFIG',
  OWNER = 'OWNER',
}
